version: "3"
services: 
  mladen-www:
    image: mladen-www
    stdin_open: true
    ports: 
      - "8080:3000"
    networks: 
      - mern-app
    depends_on: 
      - mladen-api
  mladen-api:
    image: mladen-api
    ports: 
      - "5000:5000"
    networks: 
      - mern-app
    depends_on: 
      - db
  db:
    image: mongo
    ports: 
      - "27017:27017"
    networks: 
      - mern-app
    volumes: 
      - mongo_data:/data/db
networks: 
  mern-app:
    driver: bridge
volumes: 
  mongo_data:
    driver: local

